### ISSUE TITLE
forwardとredirectの使い分け

### ISSUE THREAD

**Issue by ghost** [yamaguchi-ryo/yamaguchi_ryo#1]
https://github.com/yamaguchi-ryo/yamaguchi_ryo/blob/0be73632891749e8136af6401ba9159deedf0cf1/yamaguchi_ryo/src/chapter7/controller/HomeServlet.java#L50-L54

表題について、理解できてますか？
この場合はredirectすべきかと。

**Comment by ghost** [comment]
https://github.com/yamaguchi-ryo/yamaguchi_ryo/blob/0be73632891749e8136af6401ba9159deedf0cf1/yamaguchi_ryo/src/chapter7/controller/UserEditServlet.java#L67-L74
ここも

**Comment by yamaguchi-ryo** [comment]
どちらもredirectに変更済みです。

**Comment by ghost** [comment]
バリデーションエラーになった時、直前の値保持されてますか？
（直前の値＝画面で入力した値≠DBの最新の値）

https://github.com/yamaguchi-ryo/yamaguchi_ryo/blob/4f22c7355ae0bfec5260da2b49fec54d37aa772f/yamaguchi_ryo/src/chapter7/controller/RegistrationServlet.java#L56-L63

**Comment by yamaguchi-ryo** [comment]
inputUserをsessionで保持。registrationに飛ぶのでbranchlistとdivrollistは削除しました。
https://github.com/yamaguchi-ryo/yamaguchi_ryo/blob/9927bb6b42e94c903c052377fb938f1483f4ef9a/yamaguchi_ryo/src/chapter7/controller/RegistrationServlet.java#L44-L47

**Comment by yamaguchi-ryo** [comment]
Servletファイル全体でforward/redirectの修正を行いました。

**Comment by ghost** [comment]
sessionに入力内容を保持することで別の問題が出ているかもしれません。
以下の手順で確認をお願いします。

1. ユーザー新規登録でバリデーションエラーが出るようにフォームを入力
2. 登録ボタン押下
3. バリデーションエラーが表示されたことを確認し、ユーザー管理画面へ遷移
4. ユーザー新規登録画面へ遷移

フォームに入力内容が残っていませんか？
