### ISSUE TITLE
バリデーションエラー時のメッセージ

### ISSUE THREAD

**Issue by ghost** [yamaguchi-ryo/yamaguchi_ryo#5]
placeholderに記載はありますが、入力欄に記載がある状態で単純に「フォーマットが不正です」と言われても正解がわからないので、エラーメッセージにも表示してあげたほうが親切だと思います

**Comment by yamaguchi-ryo** [comment]
エラーメッセージに入れるように修正しました。

**Comment by ghost** [comment]
ん〜
山口くんPlaceholder好きみたいだけど、入力した見えなくなるんだから、そもそもplaceholderに書かないで、別のところに入力ルール書けば良くないですか？

**Comment by yamaguchi-ryo** [comment]
placeholderに固執していました。。
変更いたしました。
