### ISSUE TITLE
ユーザ状態の保持方法（DB）

### ISSUE THREAD

**Issue by ghost** [yamaguchi-ryo/yamaguchi_ryo#6]
すいません、これはテーブル構成のRv時の指摘漏れでもあるんですが、
ユーザの状態を"活動中"or"停止中" で保持すると、
顧客から「やっぱり“活動中“じゃなくて、“利用可能“と表示してくれ」と要求されたとき、修正めちゃめちゃ大変そうじゃないですか？
支店や部署宜しく、正規化という観点で考えて型変更とソース修正をして下さい。

**Comment by ghost** [comment]
（余談）
ここのメソッド名・変数名は若干違和感。

変数名：山口くんに関する情報全体に"山口くんの現在の状態"って名付けているような感じですよね？
メソッド名：リクエストパラメータから取得するという意味合いの"get"だと思いますが、Stringを戻している訳ではないので、fillUserStatus()とかの方が無難？原則には則っているので匙加減ではありますが...

https://github.com/yamaguchi-ryo/yamaguchi_ryo/blob/4f22c7355ae0bfec5260da2b49fec54d37aa772f/yamaguchi_ryo/src/chapter7/controller/HomeServlet.java#L37

**Comment by yamaguchi-ryo** [comment]
メソッド/変数名はそれぞれ、fillUserStatu/statusに変更しました。
復活停止情報は、DB上で0/1で保持。jsp上で0→活動中/1→停止中に変換を掛けるようにしました。
それに伴ってHomeServletのfillUserStatusにも条件分岐を足しています。
https://github.com/yamaguchi-ryo/yamaguchi_ryo/blob/5442d66b926867f63b10068e78a577e104ad83eb/yamaguchi_ryo/src/chapter7/controller/HomeServlet.java#L46-L53

**Comment by ghost** [comment]
Formから送信される値も「0」とか「1」とかに変更してはどうでしょうか？

**Comment by yamaguchi-ryo** [comment]
jspを修正し、送信される値を0/1にしました。
https://github.com/yamaguchi-ryo/yamaguchi_ryo/blob/1d970189bab3c49a93dbfcb2ed94eff88753e739/yamaguchi_ryo/src/chapter7/controller/HomeServlet.java#L46-L50

https://github.com/yamaguchi-ryo/yamaguchi_ryo/blob/1d970189bab3c49a93dbfcb2ed94eff88753e739/yamaguchi_ryo/WebContent/home.jsp#L53-L62
