### ISSUE TITLE
入力欄の値取得について

### ISSUE THREAD

**Issue by ghost** [yamaguchi-ryo/yamaguchi_ryo#7]
https://github.com/yamaguchi-ryo/yamaguchi_ryo/blob/81ea4bbb504106228511d6e2ef54a2c47c9a0163/WebContent/registration.jsp#L65

```
regi_form.loginId.value
```
この部分だけど、

```
this.value
```
に変えたら動きますかね？

**Comment by yamaguchi-ryo** [comment]
変更し動作確認済みです。
ありがとうございます。
https://github.com/yamaguchi-ryo/yamaguchi_ryo/blob/d2575154cdc878a33af4f2b224dcff2005f451b4/WebContent/registration.jsp#L64-L65
