### ISSUE TITLE
if文

### ISSUE THREAD

**Issue by ghost** [yamaguchi-ryo/yamaguchi_ryo#8]
https://github.com/yamaguchi-ryo/yamaguchi_ryo/blob/81ea4bbb504106228511d6e2ef54a2c47c9a0163/WebContent/registration.jsp#L88-L94

```
			if (value != "" && !value.match(namePattern)) {
				document.getElementById("name_error").style.display = "block";
			} else {
				document.getElementById("name_error").style.display = "none";
			}
```
これじゃダメ？

**Comment by yamaguchi-ryo** [comment]
頭が固かったです。
ありがとうございます。変更し動作確認済みです。
https://github.com/yamaguchi-ryo/yamaguchi_ryo/blob/d2575154cdc878a33af4f2b224dcff2005f451b4/WebContent/registration.jsp#L90-L97
